package de.visustruct.other

enum class XActionCommands {
    neu,
    oeffnen,
    speichern,
    speicherUnter,
    bildSpeichern,
    bildDrucken,
    bildInZwischenAblage,
    quellcodeErzeugen,
    struktogrammSchliessen,
    programmBeenden,
    simulationToggle,
    rueckgaengig,
    widerrufen,
    ganzesStruktogrammKopieren,
    letztesElementStrecken,
    schriftartAendern,
    zoomeinstellungen,
    vergroesserungenRuckgaengigMachen,
    elementShortcutsVerwenden,
    elementBeschriftungEinstellen,
    simulationEinstellen,
    info,
    lookAndFeelOSStandard,
    lookAndFeelSwingStandard,
    lookAndFeelNimbus,
    lookAndFeelFlatLight,
    lookAndFeelFlatDark,
    struktogrammbeschreibungHinzufuegen,
    languageEnglish,
    languageGerman,
    languagePortuguesePortugal,
}
