# (key, nl, pl, tr, ru) — fehlende Keys für generate_messages_nl_pl_tr_ru.py
MISSING_ENTRIES: list[tuple[str, str, str, str, str]] = [
    ("dialog.codeGen.jsBrowserIoError.message", "Het voorbeeldbestand kon niet worden aangemaakt of geopend:\n{0}", "Nie można utworzyć ani otworzyć pliku podglądu:\n{0}", "Önizleme dosyası oluşturulamadı veya açılamadı:\n{0}", "Не удалось создать или открыть файл предпросмотра:\n{0}"),
    ("dialog.codeGen.jsBrowserPageTitle", "VisuStruct", "VisuStruct", "VisuStruct", "VisuStruct"),
    (
        "dialog.codeGen.jsBrowserConsoleHint",
        "Uitvoer van console.log verschijnt in de ontwikkelaarsconsole.\n\nSafari: Safari → Instellingen → Geavanceerd → schakel «Toon menu Ontwikkelaar in de menubalk» in; daarna Ontwikkelaar → Toon JavaScript-console (macOS: ⌥⌘C).\n\nFirefox: Open hulpprogramma's voor ontwikkelaars, tabblad «Console» (macOS: ⌥⌘K; Windows: Ctrl+Shift+K).\n\nChrome: Open hulpprogramma's voor ontwikkelaars, tabblad «Console» (macOS: ⌥⌘I; Windows: F12 of Ctrl+Shift+J).\n\nMicrosoft Edge: Open hulpprogramma's voor ontwikkelaars, tabblad «Console» (Windows: F12 of Ctrl+Shift+J).",
        "Wynik console.log pojawia się w konsoli deweloperskiej.\n\nSafari: Safari → Ustawienia → Zaawansowane → włącz «Pokaż menu Programowanie na pasku menu»; następnie Programowanie → Pokaż konsolę JavaScript (macOS: ⌥⌘C).\n\nFirefox: Otwórz narzędzia deweloperskie, zakładka «Konsola» (macOS: ⌥⌘K; Windows: Ctrl+Shift+K).\n\nChrome: Otwórz narzędzia deweloperskie, zakładka «Konsola» (macOS: ⌥⌘I; Windows: F12 lub Ctrl+Shift+J).\n\nMicrosoft Edge: Otwórz narzędzia deweloperskie, zakładka «Konsola» (Windows: F12 lub Ctrl+Shift+J).",
        "console.log çıktısı geliştirici konsolunda görünür.\n\nSafari: Safari → Ayarlar → Gelişmiş → «Menü çubuğunda Geliştir menüsünü göster»i etkinleştirin; ardından Geliştir → JavaScript Konsolunu Göster (macOS: ⌥⌘C).\n\nFirefox: Geliştirici araçlarını açın, «Konsol» sekmesi (macOS: ⌥⌘K; Windows: Ctrl+Shift+K).\n\nChrome: Geliştirici araçlarını açın, «Konsol» sekmesi (macOS: ⌥⌘I; Windows: F12 veya Ctrl+Shift+J).\n\nMicrosoft Edge: Geliştirici araçlarını açın, «Konsol» sekmesi (Windows: F12 veya Ctrl+Shift+J).",
        "Вывод console.log отображается в консоли разработчика.\n\nSafari: Safari → Настройки → Дополнения → включите «Показывать меню «Разработка» в строке меню»; затем Разработка → Показать консоль JavaScript (macOS: ⌥⌘C).\n\nFirefox: Откройте инструменты разработчика, вкладка «Консоль» (macOS: ⌥⌘K; Windows: Ctrl+Shift+K).\n\nChrome: Откройте инструменты разработчика, вкладка «Консоль» (macOS: ⌥⌘I; Windows: F12 или Ctrl+Shift+J).\n\nMicrosoft Edge: Откройте инструменты разработчика, вкладка «Консоль» (Windows: F12 или Ctrl+Shift+J).",
    ),
    ("tab.untitled", "Naamloos", "Bez tytułu", "Başlıksız", "Без названия"),
    ("tab.close.tooltip", "Dit tabblad sluiten", "Zamknij tę kartę", "Bu sekmeyi kapat", "Закрыть эту вкладку"),
    ("tab.close.a11y", "Diagramtabblad sluiten", "Zamknij kartę diagramu", "Diyagram sekmesini kapat", "Закрыть вкладку диаграммы"),
    ("tab.unsaved.a11y", "Niet-opgeslagen wijzigingen", "Niezapisane zmiany", "Kaydedilmemiş değişiklikler", "Несохранённые изменения"),
    ("fileChooser.openTitle", "Openen", "Otwórz", "Aç", "Открыть"),
    ("fileChooser.saveTitle", "Opslaan", "Zapisz", "Kaydet", "Сохранить"),
    ("fileChooser.lookIn", "Zoeken in:", "Szukaj w:", "Şurada ara:", "Искать в:"),
    ("fileChooser.saveIn", "Opslaan in:", "Zapisz w:", "Şuraya kaydet:", "Сохранить в:"),
    ("fileChooser.fileName", "Bestandsnaam:", "Nazwa pliku:", "Dosya adı:", "Имя файла:"),
    ("fileChooser.filesOfType", "Bestandstype:", "Typ plików:", "Dosya türü:", "Тип файлов:"),
    ("fileChooser.open", "Openen", "Otwórz", "Aç", "Открыть"),
    ("fileChooser.openTooltip", "Geselecteerd bestand openen.", "Otwórz wybrany plik.", "Seçili dosyayı aç.", "Открыть выбранный файл."),
    ("fileChooser.save", "Opslaan", "Zapisz", "Kaydet", "Сохранить"),
    ("fileChooser.saveTooltip", "Geselecteerd bestand opslaan.", "Zapisz wybrany plik.", "Seçili dosyayı kaydet.", "Сохранить выбранный файл."),
    ("fileChooser.cancel", "Annuleren", "Anuluj", "İptal", "Отмена"),
    ("fileChooser.cancelTooltip", "Dialoog sluiten", "Zamknij okno dialogowe", "İletişim kutusunu kapat", "Закрыть диалог"),
    ("fileChooser.update", "Vernieuwen", "Odśwież", "Yenile", "Обновить"),
    ("fileChooser.updateTooltip", "Lijst vernieuwen", "Odśwież listę", "Listeyi yenile", "Обновить список"),
    ("fileChooser.newFolder", "Nieuwe map", "Nowy folder", "Yeni klasör", "Новая папка"),
    ("fileChooser.newFolderTooltip", "Nieuwe map maken", "Utwórz nowy folder", "Yeni klasör oluştur", "Создать новую папку"),
    ("fileChooser.acceptAll", "Alle bestanden", "Wszystkie pliki", "Tüm dosyalar", "Все файлы"),
    ("fileChooser.help", "Help", "Pomoc", "Yardım", "Справка"),
    ("fileChooser.helpTooltip", "Help", "Pomoc", "Yardım", "Справка"),
    ("fileChooser.newFolderError", "Map kon niet worden aangemaakt.", "Nie można utworzyć folderu.", "Klasör oluşturulamadı.", "Не удалось создать папку."),
    ("structure.element.statement", "Instructie", "Instrukcja", "İfade", "Инструкция"),
    ("structure.element.decision", "Beslissing", "Decyzja", "Karar", "Решение"),
    ("structure.element.multiway", "Meerwegkeuze (switch)", "Wybór wielokrotny (switch)", "Çok yollu seçim (switch)", "Многовариантный выбор (switch)"),
    ("structure.element.forLoop", "For-lus", "Pętla for", "For döngüsü", "Цикл for"),
    ("structure.element.whileLoop", "While-lus", "Pętla while", "While döngüsü", "Цикл while"),
    ("structure.element.doWhileLoop", "Do-while-lus", "Pętla do-while", "Do-while döngüsü", "Цикл do-while"),
    ("structure.element.infiniteLoop", "Oneindige lus", "Pętla nieskończona", "Sonsuz döngü", "Бесконечный цикл"),
    ("structure.element.breakExit", "Uitgang (break)", "Wyjście (break)", "Çıkış (break)", "Выход (break)"),
    ("structure.element.call", "Aanroep", "Wywołanie", "Çağrı", "Вызов"),
    ("structure.element.empty", "Leeg blok", "Pusty blok", "Boş blok", "Пустой блок"),
    ("structure.palette.statement", "Instructie", "Instrukcja", "İfade", "Инструкция"),
    ("structure.palette.decision", "Als", "Jeśli", "Eğer", "Если"),
    ("structure.palette.multiway", "Switch", "Switch", "Switch", "Switch"),
    ("structure.palette.forLoop", "For-lus", "Pętla for", "For döngüsü", "Цикл for"),
    ("structure.palette.whileLoop", "While-lus", "Pętla while", "While döngüsü", "Цикл while"),
    ("structure.palette.doWhileLoop", "Do-while-lus", "Pętla do-while", "Do-while döngüsü", "Цикл do-while"),
    ("structure.palette.infiniteLoop", "Oneindige lus", "Pętla nieskończona", "Sonsuz döngü", "Бесконечный цикл"),
    ("structure.palette.breakExit", "Break", "Break", "Break", "Break"),
    ("structure.palette.call", "Aanroep", "Wywołanie", "Çağrı", "Вызов"),
    ("structure.palette.empty", "Leeg", "Pusty", "Boş", "Пусто"),
    ("structure.multiway.defaultCaseLabel", "default", "default", "default", "default"),
    ("elementPreset.englishJava", "Java-achtig", "W stylu Java", "Java benzeri", "В стиле Java"),
    ("elementPreset.didacticUiLanguage", "Interface-taal", "Język interfejsu", "Arayüz dili", "Язык интерфейса"),
    ("dialog.elementText.title", "Instellingen — standaardteksten voor blokken", "Ustawienia — domyślne teksty bloków", "Ayarlar — varsayılan blok metinleri", "Настройки — тексты блоков по умолчанию"),
    ("dialog.elementText.intro", "Standaardtekst voor <b>nieuw ingevoegde</b> structuurdiagramblokken.", "Domyślny tekst dla <b>nowo wstawionych</b> bloków diagramu struktury.", "Yapı diyagramına <b>yeni eklenen</b> bloklar için varsayılan metin.", "Текст по умолчанию для <b>только что вставленных</b> блоков структурной диаграммы."),
    ("dialog.elementText.previewTitle", "Voorbeeld van standaardteksten", "Podgląd tekstów domyślnych", "Varsayılan metinlerin önizlemesi", "Предпросмотр текстов по умолчанию"),
    ("dialog.elementText.cancel", "Annuleren", "Anuluj", "İptal", "Отмена"),
    ("dialog.elementText.ok", "OK", "OK", "Tamam", "OK"),
    ("dialog.elementText.uiLanguageSection", "Taal van de interface", "Język interfejsu", "Arayüz dili", "Язык интерфейса"),
    ("dialog.elementText.simulationSection", "Simulatie", "Symulacja", "Simülasyon", "Симуляция"),
    ("dialog.elementText.simulationSpeedLabel", "Pauze tussen stappen:", "Pauza między krokami:", "Adımlar arası duraklama:", "Пауза между шагами:"),
    ("dialog.elementText.simulationSpeedUnit", "s", "s", "s", "s"),
    ("dialog.elementText.simulationHighlightLabel", "Markering in diagram:", "Podświetlenie na diagramie:", "Diyagramda vurgulama:", "Подсветка на диаграмме:"),
    ("dialog.elementText.simulationHighlightLast", "Laatst uitgevoerd", "Ostatnio wykonany", "Son çalıştırılan", "Последний выполненный"),
    ("dialog.elementText.simulationHighlightNext", "Volgende", "Następny", "Sıradaki", "Следующий"),
    ("popup.zoom", "Zoom", "Powiększenie", "Yakınlaştırma", "Масштаб"),
    ("popup.zoom.larger", "Groter", "Większy", "Daha büyük", "Крупнее"),
    ("popup.zoom.smaller", "Kleiner", "Mniejszy", "Daha küçük", "Мельче"),
    ("popup.zoom.wider", "Breder", "Szerszy", "Daha geniş", "Шире"),
    ("popup.zoom.narrower", "Smaller", "Węższy", "Daha dar", "Уже"),
    ("popup.zoom.taller", "Hoger", "Wyższy", "Daha yüksek", "Выше"),
    ("popup.zoom.shorter", "Lager", "Niższy", "Daha alçak", "Ниже"),
    ("popup.editText", "Tekst bewerken", "Edytuj tekst", "Metni düzenle", "Редактировать текст"),
    ("popup.copy", "Kopiëren", "Kopiuj", "Kopyala", "Копировать"),
    ("popup.paste", "Plakken", "Wklej", "Yapıştır", "Вставить"),
    ("popup.delete", "Verwijderen…", "Usuń…", "Sil…", "Удалить…"),
    ("popup.swapBranches", "Waar- en onwaartakken omwisselen", "Zamień gałęzie prawda i fałsz", "Doğru ve yanlış dalları değiştir", "Поменять ветви «истина» и «ложь»"),
    ("popup.insertNewCase", "Nieuw geval invoegen", "Wstaw nowy przypadek", "Yeni durum ekle", "Вставить новый случай"),
    ("popup.caseSubmenu", "Geval: {0}", "Przypadek: {0}", "Durum: {0}", "Случай: {0}"),
    ("popup.moveCaseLeft", "Geval {0} naar links verplaatsen", "Przesuń przypadek {0} w lewo", "Durumu {0} sola taşı", "Переместить случай {0} влево"),
    ("popup.moveCaseRight", "Geval {0} naar rechts verplaatsen", "Przesuń przypadek {0} w prawo", "Durumu {0} sağa taşı", "Переместить случай {0} вправо"),
    ("popup.removeCase", "Geval {0} verwijderen", "Usuń przypadek {0}", "Durumu {0} kaldır", "Удалить случай {0}"),
    ("popup.removeCaseConfirm", "Geval {0} en alle geneste blokken verwijderen?", "Usunąć przypadek {0} i wszystkie zagnieżdżone bloki?", "Durum {0} ve tüm iç içe bloklar silinsin mi?", "Удалить случай {0} и все вложенные блоки?"),
    ("popup.removeCaseTitle", "Geval verwijderen", "Usuń przypadek", "Durumu kaldır", "Удалить случай"),
    ("popup.pasteEmpty", "Nog niets gekopieerd. Gebruik eerst Kopiëren.", "Nic jeszcze nie skopiowano. Najpierw użyj Kopiuj.", "Henüz bir şey kopyalanmadı. Önce Kopyala'yı kullanın.", "Пока ничего не скопировано. Сначала используйте «Копировать»."),
    ("popup.pasteTitle", "Plakken", "Wklej", "Yapıştır", "Вставить"),
    ("palette.aboutVisuStruct", "Over VisuStruct", "O VisuStruct", "VisuStruct Hakkında", "О VisuStruct"),
    ("palette.aboutTooltip", "Over VisuStruct", "O VisuStruct", "VisuStruct Hakkında", "О VisuStruct"),
    ("palette.deleteElement", "Blok verwijderen", "Usuń blok", "Bloğu sil", "Удалить блок"),
    ("palette.generateCode", "Code genereren", "Generuj kod", "Kod oluştur", "Сгенерировать код"),
    (
        "palette.simulation.tooltip",
        "Simulatie starten of terug naar de diagrameditor",
        "Uruchom symulację lub wróć do edytora diagramu",
        "Simülasyonu başlat veya diyagram düzenleyicisine dön",
        "Запустить симуляцию или вернуться к редактору диаграммы",
    ),
    ("palette.trashDrop", "Hier neerzetten om te verwijderen", "Upuść tutaj, aby usunąć", "Silmek için buraya bırakın", "Перетащите сюда для удаления"),
    ("palette.trashClick", "Klik om het geselecteerde blok te verwijderen", "Kliknij, aby usunąć wybrany blok", "Seçili bloğu silmek için tıklayın", "Щёлкните, чтобы удалить выбранный блок"),
]
